import { test, expect } from '@playwright/test';

// Regression test for the CLS budget failure on /preise/ (CI run of 2026-09-13).
//
// Inter and JetBrains Mono were loaded with font-display: swap. On clients that
// have no local "Arial" (Ubuntu CI runners, Android) the metric-adjusted fallback
// face generated by next/font cannot load, so the first paint uses the raw system
// font and the whole page reflows once the web font arrives (CLS 0.25 desktop,
// 0.23 mobile in CI). With font-display: optional a font that misses the first
// paint is never swapped in, so a late font can no longer move anything.
//
// The web fonts are delayed here so that the first paint reliably happens before
// they are available — the situation of every real network, which a fast local
// server would otherwise hide. With font-display: optional Chromium may abort a
// font download that missed the block period; that is expected and must not
// fail the test, so the test never waits for successful font responses.

const FONT_DELAY_MS = 1500;
const BRAND_FONTS = ['Inter', 'JetBrains Mono'] as const;
const FONT_URL = /\.woff2(\?.*)?$/;
const pages = ['/', '/preise/', '/website-check/'];

type ShiftRecord = { value: number; sources: string[] };

declare global {
  interface Window {
    __layoutShifts: ShiftRecord[];
  }
}

test.describe('web fonts must not shift layout', () => {
  test.skip(({ browserName }) => browserName === 'webkit', 'Layout Instability API is Chromium-only');

  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => {
      localStorage.setItem('cookie_consent', 'denied');
      window.__layoutShifts = [];
      new PerformanceObserver((list) => {
        for (const entry of list.getEntries()) {
          const shift = entry as PerformanceEntry & {
            value: number;
            hadRecentInput: boolean;
            sources?: { node?: Node | null }[];
          };
          if (shift.hadRecentInput) continue;
          window.__layoutShifts.push({
            value: shift.value,
            sources: (shift.sources ?? []).map((s) =>
              s.node instanceof Element ? `${s.node.tagName.toLowerCase()}.${s.node.getAttribute('class') ?? ''}` : String(s.node?.nodeName),
            ),
          });
        }
      }).observe({ type: 'layout-shift', buffered: true });
    });
  });

  test('both brand font families are declared with font-display: optional', async ({ page }) => {
    await page.goto('/preise/');
    const faces = await page.evaluate(() =>
      Array.from(document.fonts).map((f) => ({ family: f.family.replace(/^["']|["']$/g, ''), display: f.display })),
    );
    const byFamily = new Map<string, string[]>();
    for (const face of faces) {
      byFamily.set(face.family, [...(byFamily.get(face.family) ?? []), face.display]);
    }
    const summary = [...byFamily].map(([family, displays]) => `${family}: ${displays.length} face(s) [${[...new Set(displays)].join(', ')}]`);

    for (const family of BRAND_FONTS) {
      const displays = byFamily.get(family);
      expect(displays, `font family "${family}" must be declared (found: ${summary.join('; ')})`).toBeDefined();
      expect(displays!.length, `font family "${family}" has no @font-face rules`).toBeGreaterThan(0);
      for (const display of displays!) {
        expect(display, `every "${family}" face must use font-display: optional (found: ${summary.join('; ')})`).toBe('optional');
      }
    }
  });

  for (const path of pages) {
    test(`${path}: late web fonts cause no layout shift`, async ({ page }) => {
      // Every intercepted font request is recorded the moment it starts and
      // settles (response or abort) only after the controlled delay.
      const interceptedFonts: string[] = [];
      const settledFonts: Promise<void>[] = [];
      await page.route(FONT_URL, (route) => {
        interceptedFonts.push(route.request().url());
        settledFonts.push(
          (async () => {
            await new Promise((resolve) => setTimeout(resolve, FONT_DELAY_MS));
            // Chromium may have aborted an optional font by now: expected.
            await route.continue().catch(() => undefined);
            await route.request().response().catch(() => null);
          })(),
        );
      });

      await page.goto(path);
      expect(interceptedFonts, 'at least one web font request must have been intercepted').not.toEqual([]);

      // The first paint is done by now. Let the delayed fonts settle, then give
      // the browser two frames to apply them (or not) and report any shift.
      await Promise.all(settledFonts);
      await page.evaluate(
        () => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(resolve, 0)))),
      );

      const shifts = await page.evaluate(() => window.__layoutShifts);
      const total = shifts.reduce((sum, s) => sum + s.value, 0);
      expect(shifts, `layout shifted after the web fonts arrived (total CLS ${total.toFixed(4)})`).toEqual([]);
    });
  }
});
