export const agbMeta = {
  stand: "18.04.2026",
  version: "3.2",
};

export type Paragraph = {
  num: string;
  title: string;
  legal: string[];
  plainTitle: string;
  plain: string[];
};

export const agb: Paragraph[] = [
  {
    num: "§ 1",
    title: "Geltungsbereich",
    legal: [
      "Diese AGB gelten für alle Verträge zwischen Michael Höger (nachfolgend „Auftragnehmer“) und dem jeweiligen Auftraggeber (nachfolgend „Kunde“) über die Erbringung von IT-Beratungs- und Webdesign-Dienstleistungen.",
      "Abweichende Bedingungen des Kunden werden nicht anerkannt, es sei denn, der Auftragnehmer stimmt ihrer Geltung ausdrücklich schriftlich zu.",
      "Diese AGB gelten sowohl gegenüber Unternehmern (§ 14 BGB) als auch gegenüber Verbrauchern (§ 13 BGB). Für Verbraucher gelten zusätzlich bzw. abweichend die Sonderregelungen in § 13 dieser AGB (inkl. Widerrufsbelehrung).",
    ],
    plainTitle: "Wann gelten diese Regeln?",
    plain: [
      "Diese Regeln gelten, wenn Sie mich mit einem Projekt beauftragen — egal ob Webseite, Beratung oder etwas anderes.",
      "Eigene Bedingungen von Ihrer Seite übernehme ich nur, wenn wir das vorher schriftlich abgesprochen haben.",
      "Ob Sie Unternehmen oder Privatperson sind: Diese AGB gelten für beide. Als Privatperson haben Sie zusätzliche Rechte — insbesondere ein 14-tägiges Widerrufsrecht. Die Details dazu stehen weiter unten in § 13.",
    ],
  },
  {
    num: "§ 2",
    title: "Leistungsumfang",
    legal: [
      "Art und Umfang der Leistungen ergeben sich aus dem jeweiligen Angebot bzw. der Auftragsbestätigung.",
      "Einzelprojekte mit definiertem Leistungsumfang (z. B. Erstellung einer Website) werden als Werkvertrag (§§ 631 ff. BGB) erbracht. Laufende Leistungen ohne definierten Erfolg (z. B. Beratung, Retainer, laufende Betreuung) werden als Dienstvertrag (§§ 611 ff. BGB) erbracht. Die vertragliche Einordnung ergibt sich aus dem jeweiligen Angebot.",
      "Änderungswünsche des Kunden, die über den vereinbarten Leistungsumfang hinausgehen, bedürfen einer gesonderten Vereinbarung und werden zusätzlich vergütet.",
      "Der Auftragnehmer erbringt seine Leistungen nach anerkannten Regeln der Technik unter Einsatz aktueller Technologien und Standards.",
    ],
    plainTitle: "Was ich für Sie mache",
    plain: [
      "Was genau ich mache, steht in Ihrem Angebot. Das ist der Maßstab für alle Beteiligten.",
      "Rechtlich wird unterschieden: Bei einem fixen Projekt mit klarem Ergebnis (z. B. fertige Website) schulde ich Ihnen das Ergebnis (Werkvertrag). Bei laufender Betreuung ohne festes Ergebnis (z. B. Beratung, Retainer) schulde ich Ihnen die Leistung an sich (Dienstvertrag). Was in Ihrem Fall gilt, steht im Angebot.",
      "Wenn Sie unterwegs zusätzliche Dinge brauchen, die nicht im Angebot stehen, besprechen wir das kurz und ich kalkuliere den Aufwand extra.",
      "Ich arbeite nach anerkannten Regeln der Technik mit aktuellen Werkzeugen — nicht mit veraltetem Zeug von vorgestern.",
    ],
  },
  {
    num: "§ 3",
    title: "Mitwirkungspflichten des Kunden",
    legal: [
      "Der Kunde stellt dem Auftragnehmer alle für die Durchführung des Auftrags erforderlichen Unterlagen, Daten und Zugänge rechtzeitig und kostenlos zur Verfügung (z. B. Texte, Bilder, Logos, Markenrichtlinien, Farbvorgaben, Domain-Zugänge, Hosting-Zugangsdaten). Die vollständige und rechtzeitige Zuarbeit ist Voraussetzung für die fristgerechte Leistungserbringung.",
      "Der Kunde benennt einen Ansprechpartner, der für Rückfragen und Freigaben zur Verfügung steht.",
      "Verzögerungen, die durch fehlende Mitwirkung des Kunden entstehen, gehen nicht zu Lasten des Auftragnehmers. Vereinbarte Termine verschieben sich entsprechend.",
      "Kommt der Kunde seinen Mitwirkungspflichten trotz schriftlicher Aufforderung mit angemessener Fristsetzung (mindestens 14 Kalendertage) nicht nach, ist der Auftragnehmer berechtigt, das Projekt bis zur Bereitstellung der ausstehenden Zuarbeit ruhen zu lassen. Entsteht durch die Verzögerung Mehraufwand (z. B. erneute Einarbeitung, Neuplanung), wird dieser nach Aufwand auf Basis des im Angebot vereinbarten Stundensatzes berechnet.",
      "Bleibt die Mitwirkung des Kunden nach erneuter Fristsetzung von 14 Kalendertagen aus, ist der Auftragnehmer berechtigt, den Vertrag außerordentlich zu kündigen. Die bis dahin erbrachten Leistungen sind vollständig zu vergüten.",
    ],
    plainTitle: "Was Sie mir zuarbeiten müssen",
    plain: [
      "Damit ich arbeiten kann, brauche ich von Ihnen Texte, Bilder, Logo, Markenrichtlinien und Zugänge zu Ihrer Domain und Ihrem Hosting. Pünktlich und ohne Extrakosten für mich. Nur so kann ich Termine einhalten.",
      "Bitte benennen Sie eine Person bei Ihnen, die ich bei Fragen direkt ansprechen kann und die Freigaben erteilen darf.",
      "Wenn ich wegen fehlender Zuarbeit warten muss, verschieben sich vereinbarte Termine automatisch — dafür kann ich nichts.",
      "Wenn Sie trotz schriftlicher Erinnerung und 14 Tagen Frist nichts liefern, lege ich das Projekt pausiert. Entsteht dadurch Mehraufwand (z. B. weil ich mich später wieder einarbeiten muss), rechne ich den nach Stunden ab.",
      "Bleibt auch nach einer zweiten 14-Tage-Frist die Zuarbeit aus, darf ich den Vertrag beenden. Was bis dahin gemacht ist, wird voll bezahlt.",
    ],
  },
  {
    num: "§ 4",
    title: "Angebot und Vertragsschluss",
    legal: [
      "Angebote des Auftragnehmers sind freibleibend und 14 Tage gültig, sofern nicht anders angegeben.",
      "Der Vertrag kommt durch schriftliche Auftragsbestätigung des Auftragnehmers oder durch Aufnahme der Leistungserbringung zustande. Schriftform umfasst auch E-Mail.",
    ],
    plainTitle: "Wie kommt unser Vertrag zustande?",
    plain: [
      "Meine Angebote sind 14 Tage gültig, wenn nicht anders vereinbart.",
      "Der Vertrag gilt, sobald ich Ihren Auftrag schriftlich bestätige oder mit der Arbeit beginne. E-Mail reicht — kein Fax und keine Unterschrift in Blut nötig.",
    ],
  },
  {
    num: "§ 5",
    title: "Vergütung und Zahlungsbedingungen",
    legal: [
      "Die Vergütung richtet sich nach dem jeweiligen Angebot. Alle Preise verstehen sich als Endpreise. Gemäß § 19 UStG wird keine Umsatzsteuer berechnet.",
      "Bei Projekten mit einem Volumen über 500 € ist eine Anzahlung von 50 % bei Auftragserteilung fällig. Die Restzahlung erfolgt nach Abnahme.",
      "Rechnungen sind innerhalb von 14 Tagen nach Rechnungsdatum ohne Abzug zahlbar.",
      "Laufende Leistungen (z. B. Hosting- und Wartungsverträge, Retainer) werden monatlich im Voraus berechnet.",
      "Bei Zahlungsverzug ist der Auftragnehmer berechtigt, Verzugszinsen in Höhe von 9 Prozentpunkten über dem Basiszinssatz (bei Verbrauchern 5 Prozentpunkte, siehe § 13) sowie die gesetzliche Verzugspauschale nach § 288 Abs. 5 BGB (40 €, nur gegenüber Unternehmern) zu berechnen und laufende Arbeiten bis zum Zahlungseingang auszusetzen.",
      "Bei laufenden Verträgen (Hosting, Wartung, Retainer) ist der Auftragnehmer berechtigt, die Vergütung einmal jährlich im Umfang der Veränderung des Verbraucherpreisindex (VPI, veröffentlicht vom Statistischen Bundesamt) anzupassen, maximal jedoch 5 % pro Anpassung. Die Anpassung ist dem Kunden mit einer Frist von mindestens 4 Wochen in Textform anzukündigen. Der Kunde hat ein Sonderkündigungsrecht zum Wirksamwerden der Anpassung.",
    ],
    plainTitle: "Preise und Zahlung",
    plain: [
      "Was Sie zahlen, steht im Angebot — als Endpreis. Ich bin Kleinunternehmer, deshalb kommt keine Mehrwertsteuer dazu.",
      "Bei Projekten über 500 € teile ich die Zahlung: 50 % bei Projektstart, die restlichen 50 % nach Fertigstellung.",
      "Rechnungen zahlen Sie bitte innerhalb von 14 Tagen.",
      "Laufende Sachen wie Hosting und Wartung rechne ich monatlich im Voraus ab.",
      "Wenn eine Zahlung ausbleibt, darf ich gesetzliche Verzugszinsen berechnen und pausiere so lange, bis das Geld da ist. Privatpersonen zahlen niedrigere Zinsen als Unternehmen — das ist gesetzlich so geregelt.",
      "Bei laufenden Verträgen (Hosting, Wartung) darf ich einmal im Jahr die Preise anpassen, wenn die allgemeinen Preise steigen — maximal 5 % und höchstens so viel wie die Inflationsrate. Ich kündige das mindestens 4 Wochen vorher per E-Mail an, und Sie dürfen zu diesem Zeitpunkt außerordentlich kündigen, wenn Sie nicht einverstanden sind.",
    ],
  },
  {
    num: "§ 6",
    title: "Projektablauf und Abnahme",
    legal: [
      "Der Auftragnehmer stellt dem Kunden Zwischenstände zur Abstimmung bereit.",
      "Die Anzahl der je Projektphase im Projektpreis enthaltenen Korrekturschleifen ergibt sich aus dem jeweiligen Angebot. Weitere Korrekturen werden nach Aufwand berechnet.",
      "Nach Fertigstellung wird der Kunde zur Abnahme aufgefordert. Die Abnahme gilt als erfolgt, wenn der Kunde nicht innerhalb von 14 Kalendertagen nach Aufforderung nachvollziehbare Mängel in Textform benennt. Der Kunde wird mit der Aufforderung zur Abnahme ausdrücklich auf die Bedeutung dieser Frist und die Folgen seines Schweigens (konkludente Abnahme) hingewiesen.",
      "Die Abnahme gilt ebenfalls als erteilt, wenn der Kunde die Leistung im produktiven Betrieb nutzt (z. B. Veröffentlichung der Website, Nutzung gegenüber Dritten) — unabhängig davon, ob eine ausdrückliche Abnahmeerklärung vorliegt.",
      "Geringfügige Abweichungen, die die Funktionalität nicht beeinträchtigen, berechtigen nicht zur Verweigerung der Abnahme.",
      "Bei mehrphasigen Projekten können im Angebot oder Projektvertrag Teilabnahmen pro Projektphase (z. B. Konzept, Design, Entwicklung) vereinbart werden. Die Regelungen dieses Paragraphen gelten in diesem Fall entsprechend für jede einzelne Phase; die Rechtsfolgen der Abnahme (insbesondere Beginn der Gewährleistungsfrist, Fälligkeit der Phasenvergütung, Gefahrtragung) treten mit Abnahme der jeweiligen Phase ein.",
    ],
    plainTitle: "So läuft das Projekt ab",
    plain: [
      "Ich zeige Ihnen Zwischenstände, damit Sie sehen, wo wir stehen und nicht am Ende eine böse Überraschung erleben.",
      "Wie viele Korrekturrunden pro Projektphase in Ihrem Preis enthalten sind, steht in Ihrem Angebot — das hängt vom gebuchten Paket ab. Zusätzliche Runden rechne ich nach Aufwand ab.",
      "Wenn's fertig ist, bitte ich Sie um Ihr OK („Abnahme“). Wenn Sie innerhalb von 14 Tagen nicht konkret sagen, was noch nicht passt, gilt das Projekt als abgenommen.",
      "Sobald Sie die Webseite aktiv in Ihrem Geschäft nutzen oder gegenüber Ihren Kunden einsetzen, gilt das automatisch als Abnahme — auch ohne formelle Freigabe.",
      "Kleine Abweichungen, die nichts kaputtmachen, sind kein Grund, die Abnahme zu verweigern.",
      "Bei größeren Projekten können wir Abnahmen in Etappen machen — zum Beispiel nach Konzept, nach Design und nach der Entwicklung. Jede abgenommene Etappe wird abgerechnet, und die Gewährleistung beginnt für diesen Teil zu laufen.",
    ],
  },
  {
    num: "§ 7",
    title: "Nutzungsrechte",
    legal: [
      "Mit vollständiger Bezahlung erhält der Kunde ein einfaches, zeitlich und räumlich unbeschränktes Nutzungsrecht an den erstellten Werken für den im Vertrag definierten Zweck. Ein ausschließliches (exklusives) Nutzungsrecht wird nur bei ausdrücklicher schriftlicher Vereinbarung eingeräumt.",
      "Der Auftragnehmer ist berechtigt, zugrundeliegende generische Bausteine (eigene Code-Komponenten, Vorlagen, wiederverwendbare Module), die nicht individuell für den Kunden gestaltet wurden, auch in anderen Projekten einzusetzen.",
      "Das Nutzungsrecht umfasst die Verwendung, Veröffentlichung und Darstellung der Werke im vereinbarten Rahmen. Eine Bearbeitung oder Weiterentwicklung durch den Kunden oder Dritte ist zulässig; bei wesentlichen Änderungen darf der Auftragnehmer nicht mehr als Urheber der bearbeiteten Version genannt werden.",
      "Die Weitergabe der Nutzungsrechte an Dritte bedarf der vorherigen schriftlichen Zustimmung des Auftragnehmers, es sei denn, die Weitergabe erfolgt im Rahmen eines Unternehmensverkaufs oder einer Rechtsnachfolge.",
      "Der Auftragnehmer behält das Recht, die erstellten Arbeiten in seinem Portfolio und zu Referenzzwecken zu verwenden, sofern der Kunde dem nicht binnen 4 Wochen nach Abnahme in Textform widerspricht.",
      "Verwendete Open-Source-Komponenten und Drittanbieter-Lizenzen unterliegen deren jeweiligen Lizenzbedingungen. Der Auftragnehmer informiert den Kunden hierüber.",
      "Bis zur vollständigen Bezahlung verbleiben sämtliche Nutzungsrechte beim Auftragnehmer.",
    ],
    plainTitle: "Was gehört Ihnen am Ende?",
    plain: [
      "Sobald Sie die Rechnung beglichen haben, dürfen Sie alles, was ich für Sie erstellt habe, unbegrenzt für Ihren Zweck nutzen. Standard ist ein „einfaches Nutzungsrecht“: Sie nutzen Ihr fertiges Werk frei, ich darf aber die zugrundeliegenden Bausteine (Code-Komponenten, Vorlagen) auch in anderen Kundenprojekten wiederverwenden. Wollen Sie, dass ich genau dieses konkrete Werk niemandem sonst zur Verfügung stelle („ausschließliches Nutzungsrecht“), vereinbaren wir das extra schriftlich — das kostet in der Regel Aufpreis.",
      "Sie dürfen das Werk ändern, erweitern oder von einer anderen Agentur überarbeiten lassen — das ist Ihr gutes Recht. Eine Einschränkung: Wenn das Ergebnis stark von meiner ursprünglichen Arbeit abweicht, darf mein Name nicht mehr als Urheber dabeistehen. Das schützt mich davor, dass schlechte oder entstellte Umbauten auf mich zurückfallen.",
      "Wenn Sie die Rechte an jemand anderen weitergeben wollen, fragen Sie mich bitte kurz. Ausnahme: Sie verkaufen Ihre Firma oder vererben sie — dann geht alles automatisch mit.",
      "Ich darf Ihre Projekte in meinem Portfolio zeigen, um neue Kunden zu gewinnen — es sei denn, Sie widersprechen innerhalb von 4 Wochen nach Fertigstellung schriftlich.",
      "Für Ihre Webseite nutze ich fertige Bausteine wie Frameworks, Schriftarten und Icons. Das ist Standard und spart Ihnen Geld. Bei Projektübergabe bekommen Sie eine kurze Liste, was ich verwendet habe. Meistens müssen Sie gar nichts tun — die Bausteine sind frei nutzbar. Nur in seltenen Fällen gibt es Besonderheiten, auf die ich Sie dann extra hinweise.",
      "Bis die Rechnung bezahlt ist, bleiben alle Rechte bei mir.",
    ],
  },
  {
    num: "§ 8",
    title: "Gewährleistung",
    legal: [
      "Der Auftragnehmer gewährleistet, dass die erbrachten Leistungen dem vereinbarten Leistungsumfang entsprechen.",
      "Mängel sind unverzüglich, spätestens innerhalb von 14 Tagen nach Entdeckung, in Textform (E-Mail genügt) zu melden.",
      "Bei berechtigten Mängeln hat der Auftragnehmer das Recht zur Nachbesserung innerhalb einer angemessenen Frist. Gelingt die Nachbesserung nach zwei Versuchen nicht, kann der Kunde die Vergütung mindern oder vom Vertrag zurücktreten.",
      "Die Gewährleistungsfrist gegenüber Unternehmern beträgt 12 Monate ab Abnahme. Gegenüber Verbrauchern gilt die gesetzliche Gewährleistungsfrist (siehe § 13).",
      "Von der Gewährleistung ausgenommen sind Mängel, die durch nachträgliche Änderungen des Kunden oder Dritter, durch unsachgemäße Nutzung oder durch Änderungen der technischen Umgebung (z. B. Browser-Updates, Betriebssystem-Updates, Hosting-Wechsel) entstehen. Für die laufende Anpassung an solche Veränderungen bietet der Auftragnehmer separate Wartungsverträge an.",
      "Ein Mangel liegt nur vor, wenn die Leistung von der im Angebot oder Projektvertrag vereinbarten Beschaffenheit abweicht. Nachträgliche Änderungswünsche des Kunden, die über den vereinbarten Leistungsumfang hinausgehen (insbesondere Design-Iterationen nach erfolgter Freigabe, funktionale Erweiterungen, Layout- oder Strukturumbauten), gelten nicht als Mangel, sondern als Änderungswunsch im Sinne von § 2 (3) und werden gesondert vergütet.",
    ],
    plainTitle: "Was, wenn etwas nicht passt?",
    plain: [
      "Ich garantiere Ihnen, dass Sie das bekommen, was im Angebot vereinbart war.",
      "Wenn Sie einen Fehler entdecken, melden Sie ihn mir bitte innerhalb von 14 Tagen per E-Mail.",
      "Wenn der Fehler berechtigt ist, bessere ich ihn in einer fairen Frist nach — kostenlos. Klappt das zweimal nicht, können Sie den Preis mindern oder vom Vertrag zurücktreten.",
      "Für Unternehmen läuft die Gewährleistung 12 Monate ab Abnahme. Privatpersonen haben gesetzlich 2 Jahre — die Details dazu stehen in § 13.",
      "Nicht abgedeckt sind Probleme, die nach der Abnahme entstehen: nachträgliche Änderungen durch Sie oder Dritte, falsche Nutzung, oder Änderungen an der Technik drumherum (Browser-Update, neuer Hosting-Anbieter, neue Handy-Betriebssystem-Version). Das ist keine Gewährleistungssache, sondern fällt unter Wartung — dafür können Sie einen Wartungsvertrag buchen, damit Ihre Webseite über die Jahre kompatibel und sicher bleibt.",
      "Neue Features oder Umbauten am Bestehenden sind kein Gewährleistungsfall: Das beauftragen Sie bei Bedarf als neues Projekt. Auch Design-Iterationen, nachdem Sie etwas schon freigegeben haben, zähle ich als Änderungswunsch und rechne sie separat ab.",
    ],
  },
  {
    num: "§ 9",
    title: "Haftung",
    legal: [
      "Der Auftragnehmer haftet unbeschränkt bei Vorsatz und grober Fahrlässigkeit sowie bei Verletzung von Leben, Körper und Gesundheit.",
      "Bei leichter Fahrlässigkeit haftet der Auftragnehmer nur bei Verletzung wesentlicher Vertragspflichten (Kardinalpflichten). Die Haftung ist in diesem Fall auf den vorhersehbaren, vertragstypischen Schaden begrenzt.",
      "Die Haftung ist bei Einzelprojekten auf die Höhe der vereinbarten Vergütung begrenzt. Bei laufenden Verträgen (Hosting, Wartung, Retainer) ist die Haftung auf die Summe der in den letzten 12 Monaten gezahlten Vergütung begrenzt.",
      "Die Haftung für entgangenen Gewinn, entgangene Umsätze (insbesondere durch Ausfall der Website, Rankingverluste oder SEO-Veränderungen), Datenverlust und mittelbare Schäden ist bei leichter Fahrlässigkeit ausgeschlossen. Soweit der Auftragnehmer Hosting oder eine laufende Wartung übernommen hat, führt er regelmäßige Datensicherungen nach einem dokumentierten Backup-Konzept durch (tägliche Sicherung, mehrstufige Aufbewahrung, Offsite-Ablage bei einem zweiten Anbieter). Das Backup-Konzept wird dem Kunden auf Anfrage in Textform ausgehändigt. In allen anderen Fällen obliegt die Datensicherung dem Kunden; bei unterlassener angemessener Datensicherung haftet der Auftragnehmer für Datenverluste nicht.",
      "Der Auftragnehmer haftet nicht für Störungen, Ausfälle oder Sicherheitsvorfälle, die durch Drittanbieter-Dienste oder deren Veränderungen verursacht werden (z. B. Hosting-Provider, Domain-Registrar, externe APIs und deren Änderungen, CMS- und Framework-Plugins, SaaS-Dienste mit Breaking Changes, Software- oder Schnittstellen-Updates, Content-Delivery-Netzwerke). Gleiches gilt für Schäden durch höhere Gewalt.",
    ],
    plainTitle: "Wer haftet wofür?",
    plain: [
      "Wenn ich absichtlich oder grob nachlässig Mist baue — oder wenn jemand durch einen Fehler von mir körperlich zu Schaden kommt — hafte ich voll, ohne Einschränkung. Der zweite Punkt ist eine gesetzliche Standardklausel, die in jeder AGB steht; bei Webdesign sind solche Fälle theoretisch (z. B. epilepsieauslösende Animationen), praktisch extrem selten.",
      "Bei kleinen Versehen hafte ich nur, wenn ich eine richtig wichtige Vertragspflicht verletze, und auch dann nur für den Schaden, mit dem man typischerweise rechnen muss.",
      "Die Summe, für die ich maximal gerade stehe, ist bei Einzelprojekten der Projektpreis. Bei laufenden Verträgen (Hosting, Wartung) die Summe, die Sie mir in den letzten 12 Monaten gezahlt haben.",
      "Entgangene Gewinne, entgangene Umsätze (zum Beispiel durch einen Website-Ausfall oder Verschlechterungen im Google-Ranking), Datenverluste oder Folgeschäden sind bei kleinen Versehen nicht dabei. Wenn ich Ihre Webseite hoste oder einen Wartungsvertrag mit Ihnen habe, kümmere ich mich um regelmäßige Backups nach einem festen Konzept (tägliche Sicherungen, mehrere Aufbewahrungsstufen, ausgelagert bei einem zweiten Anbieter) — das Backup-Konzept sende ich Ihnen gerne auf Anfrage zu. Hosten Sie selbst oder haben Sie keinen Wartungsvertrag, sind Sie für Backups verantwortlich.",
      "Wenn Ihr Hosting-Anbieter, der Domain-Dienst, eine externe Schnittstelle, ein Plugin oder ein anderer Fremd-Dienst ausfällt, sich ändert oder gehackt wird, kann ich nichts dafür. Das gilt auch für höhere Gewalt wie Stromausfälle oder Internet-Probleme.",
    ],
  },
  {
    num: "§ 10",
    title: "Vertraulichkeit",
    legal: [
      "Beide Parteien verpflichten sich, vertrauliche Informationen der jeweils anderen Partei nicht an Dritte weiterzugeben und nur für die Zwecke der Zusammenarbeit zu verwenden.",
      "Diese Verpflichtung besteht auch nach Beendigung des Vertrages fort, längstens jedoch für 5 Jahre nach Vertragsende. Offenkundige oder gesetzlich offenzulegende Informationen sind ausgenommen.",
    ],
    plainTitle: "Was unter uns bleibt",
    plain: [
      "Was Sie mir im Projekt anvertrauen (Passwörter, Geschäftszahlen, Strategien), gebe ich nicht weiter und nutze es nur für unser Projekt. Umgekehrt genauso.",
      "Das gilt auch nach Projektende — bis zu 5 Jahre lang. Allgemein bekannte Informationen oder Dinge, die ich gesetzlich offenlegen muss (z. B. gegenüber dem Finanzamt), sind davon ausgenommen.",
    ],
  },
  {
    num: "§ 11",
    title: "Datenschutz",
    legal: [
      "Der Auftragnehmer verarbeitet personenbezogene Daten des Kunden ausschließlich im Rahmen der gesetzlichen Bestimmungen (DSGVO, BDSG) und der Datenschutzerklärung, einsehbar unter hoeger.dev/datenschutz.",
      "Soweit der Auftragnehmer im Rahmen der Leistungserbringung personenbezogene Daten Dritter (z. B. Website-Besucher, Kundendaten des Kunden) im Auftrag des Kunden verarbeitet, schließen die Parteien einen Auftragsverarbeitungsvertrag (AVV) nach Art. 28 DSGVO. Der AVV wird als separates Dokument bereitgestellt.",
      "Beide Parteien sind verpflichtet, angemessene technische und organisatorische Maßnahmen (TOMs) zum Schutz personenbezogener Daten zu treffen.",
      "Rollen nach DSGVO: Soweit der Auftragnehmer personenbezogene Daten im Auftrag des Kunden verarbeitet (z. B. beim Hosting der Website des Kunden, bei laufender Pflege von Kundendaten im CMS, bei Auswertung von Besucherstatistiken im Auftrag), handelt er als Auftragsverarbeiter (Art. 28 DSGVO); Grundlage ist der separate AVV. Verarbeitet der Auftragnehmer Daten zu eigenen Zwecken (z. B. Buchhaltung, Kundenkommunikation, Rechnungsstellung), ist er Verantwortlicher (Art. 4 Nr. 7 DSGVO). Bei reiner Beratungsleistung ohne Zugriff auf personenbezogene Daten entsteht keine Auftragsverarbeitung.",
    ],
    plainTitle: "Wie ich mit Daten umgehe",
    plain: [
      "Ich halte mich an den Datenschutz (DSGVO). Meine Datenschutzerklärung finden Sie auf hoeger.dev/datenschutz.",
      "Sobald ich für Sie Daten anderer Menschen verarbeite (z. B. Besucher Ihrer Webseite oder Ihre Kundendaten im CMS), schließen wir zusätzlich einen Auftragsverarbeitungsvertrag (AVV). Das ist ein Standarddokument, das der Datenschutz vorschreibt — ich bringe es fertig mit.",
      "Beide Seiten — Sie und ich — müssen Daten vernünftig sichern. Ich nutze SSL-Verschlüsselung, sichere Passwörter, Backups und regelmäßige Updates. Welche Maßnahmen Sie auf Ihrer Seite brauchen, besprechen wir im Projekt.",
      "In der Datenschutz-Welt gibt es zwei Rollen: Wenn ich für Sie Daten Ihrer Kunden verarbeite (z. B. beim Hosting), bin ich „Auftragsverarbeiter“ — dafür gibt es den AVV. Wenn ich meine eigenen Daten verarbeite (z. B. für meine Buchhaltung), bin ich selbst verantwortlich. Wenn ich Sie nur berate, ohne auf Daten Ihrer Kunden zuzugreifen, braucht es gar keinen AVV.",
    ],
  },
  {
    num: "§ 12",
    title: "Kündigung",
    legal: [
      "Festpreisprojekte (Werkverträge) können vom Kunden jederzeit in Textform gekündigt werden. In diesem Fall sind die bis dahin nachweislich erbrachten Leistungen zu vergüten. Die Berechnung erfolgt auf Basis des im Angebot vereinbarten Stundensatzes multipliziert mit den geleisteten Stunden, mindestens jedoch in Höhe der vereinbarten Anzahlung, soweit diese bereits fällig war. Der Auftragnehmer legt dem Kunden eine nachvollziehbare Aufstellung der erbrachten Leistungen vor. Das Recht des Auftragnehmers nach § 648 BGB (Vergütung abzüglich ersparter Aufwendungen) bleibt unberührt.",
      "Laufende Verträge (Hosting, Wartung, Retainer) können von beiden Seiten mit einer Frist von 30 Tagen zum Monatsende in Textform gekündigt werden, sofern im Angebot keine abweichende Mindestlaufzeit oder Kündigungsfrist vereinbart wurde.",
      "Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt. Ein wichtiger Grund liegt insbesondere vor bei Zahlungsverzug von mehr als 30 Tagen trotz Mahnung, bei wiederholter Verletzung wesentlicher Vertragspflichten oder bei Eröffnung eines Insolvenzverfahrens über das Vermögen einer Partei.",
    ],
    plainTitle: "Wie wir auseinandergehen",
    plain: [
      "Bei Festpreisprojekten können Sie jederzeit per E-Mail aussteigen. Sie zahlen dann, was ich bis dahin geleistet habe — berechnet nach Stundensatz mal den tatsächlichen Stunden, mindestens aber die fällige Anzahlung. Ich zeige Ihnen transparent, was ich schon gemacht habe. Im Gesetz steht auch, dass mir bei einem Projekt-Stopp grundsätzlich der volle Preis zusteht, abzüglich dessen, was ich mir durch den Abbruch spare — das ist der gesetzliche Standard.",
      "Laufende Verträge (Hosting, Wartung, Retainer) können beide Seiten mit 30 Tagen Frist zum Monatsende per E-Mail kündigen. Wenn im Angebot eine andere Mindestlaufzeit oder Kündigungsfrist steht, gilt die.",
      "Aus wichtigem Grund kann jede Seite sofort raus — zum Beispiel wenn eine Rechnung über 30 Tage trotz Mahnung nicht bezahlt wurde, wesentliche Pflichten immer wieder verletzt werden, oder eine Seite in Insolvenz gerät.",
    ],
  },
  {
    num: "§ 13",
    title: "Sonderregelungen für Verbraucher",
    legal: [
      "Dieser Paragraph gilt ausschließlich für Verträge mit Verbrauchern im Sinne des § 13 BGB. Bei Widersprüchen zu den vorstehenden Paragraphen gehen die Regelungen dieses § 13 vor.",
      "Gewährleistung: Die Gewährleistungsfrist beträgt bei Verbrauchern 2 Jahre ab Abnahme. Die Regelung in § 8 (4) findet keine Anwendung.",
      "Verzugszinsen: Bei Zahlungsverzug beträgt der Verzugszinssatz 5 Prozentpunkte über dem Basiszinssatz (§ 288 Abs. 1 BGB). Die Verzugspauschale nach § 288 Abs. 5 BGB (40 €) findet keine Anwendung.",
      "Gerichtsstand: Die Regelung in § 14 (2) findet keine Anwendung. Gerichtsstand ist der gesetzliche.",
      "Online-Streitbeilegung: Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS-Plattform) bereit: ec.europa.eu/consumers/odr. Der Auftragnehmer ist weder verpflichtet noch bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen (§ 36 VSBG).",
      "Widerrufsrecht: Sie haben das Recht, binnen 14 Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt 14 Tage ab dem Tag des Vertragsabschlusses.",
      "Um Ihr Widerrufsrecht auszuüben, müssen Sie Michael Höger, Johann-Boppe-Str. 19, 65549 Limburg an der Lahn, E-Mail: michael@hoeger.dev, mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das Muster-Widerrufsformular (Anlage 1) verwenden, das jedoch nicht vorgeschrieben ist. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.",
      "Folgen des Widerrufs: Wenn Sie diesen Vertrag widerrufen, hat der Auftragnehmer Ihnen alle Zahlungen, die er von Ihnen erhalten hat, unverzüglich und spätestens binnen 14 Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrages bei ihm eingegangen ist. Für diese Rückzahlung wird dasselbe Zahlungsmittel verwendet, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.",
      "Vorzeitiges Erlöschen des Widerrufsrechts: Haben Sie verlangt, dass die Dienstleistungen während der Widerrufsfrist beginnen sollen, so haben Sie dem Auftragnehmer einen angemessenen Betrag zu zahlen, der dem Anteil der bis zum Zeitpunkt, zu dem Sie den Auftragnehmer von der Ausübung des Widerrufsrechts hinsichtlich dieses Vertrages unterrichten, bereits erbrachten Dienstleistungen im Vergleich zum Gesamtumfang der im Vertrag vorgesehenen Dienstleistungen entspricht. Das Widerrufsrecht erlischt vorzeitig, wenn der Vertrag von beiden Seiten auf Ihren ausdrücklichen Wunsch vollständig erfüllt worden ist, bevor Sie Ihr Widerrufsrecht ausgeübt haben.",
    ],
    plainTitle: "Was gilt besonders für Privatpersonen?",
    plain: [
      "Wenn Sie Privatperson sind (also Verbraucher), gelten für Sie ein paar Dinge anders als für Firmen. Dieser Abschnitt sammelt alle Sonderregeln. Falls sich etwas widerspricht: Die Regeln hier haben Vorrang.",
      "Gewährleistung: Statt 12 Monate haben Sie die volle gesetzliche Gewährleistung von 2 Jahren ab Abnahme.",
      "Verzugszinsen: Wenn Sie mit einer Zahlung im Verzug sind, berechne ich niedrigere Zinsen (5 Prozentpunkte über dem Basiszinssatz). Die 40-€-Pauschale für Unternehmen gilt für Sie nicht.",
      "Gerichtsstand: Für Sie gilt der gesetzliche Gerichtsstand — also meistens das Gericht, das für Ihren Wohnort zuständig ist, nicht Limburg.",
      "Online-Streitbeilegung: Die EU stellt eine Plattform für Online-Streitbeilegung bereit (ec.europa.eu/consumers/odr). Ich bin nicht verpflichtet, an Schlichtungsverfahren teilzunehmen, und werde das auch nicht tun — bei Streit suchen wir lieber direkt das Gespräch.",
      "Widerrufsrecht: Sie können innerhalb von 14 Tagen nach Vertragsabschluss ohne Grund widerrufen. Eine kurze E-Mail an michael@hoeger.dev reicht (oder ein Brief, oder das Muster-Formular weiter unten in Anlage 1). Die Frist ist gewahrt, wenn Sie die Nachricht rechtzeitig absenden.",
      "Folgen des Widerrufs: Wenn Sie widerrufen, zahle ich Ihnen innerhalb von 14 Tagen alles zurück, was Sie schon gezahlt haben — auf demselben Weg, auf dem Sie bezahlt haben. Keine Extra-Gebühren.",
      "Wichtig: Wenn Sie wollen, dass ich gleich nach Vertragsabschluss loslege (und nicht die 14 Tage abwarte), müssen Sie für die bis zum Widerruf schon erbrachten Leistungen anteilig zahlen. Wenn das Projekt auf Ihren Wunsch schon komplett fertig ist, erlischt das Widerrufsrecht vorzeitig — dann geht nichts mehr zurück. Diese Möglichkeit steht auch im Projektvertrag und ist Ihre Entscheidung.",
    ],
  },
  {
    num: "§ 14",
    title: "Schlussbestimmungen",
    legal: [
      "Es gilt das Recht der Bundesrepublik Deutschland.",
      "Gerichtsstand ist Limburg an der Lahn, sofern der Kunde Kaufmann, juristische Person des öffentlichen Rechts oder öffentlich-rechtliches Sondervermögen ist. Für Verbraucher siehe § 13 (4).",
      "Sollten einzelne Bestimmungen dieser AGB unwirksam sein oder werden, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt.",
      "Änderungen und Ergänzungen dieser AGB bedürfen der Textform.",
      "Bei Meinungsverschiedenheiten zur Auslegung dieser AGB oder zum Projektinhalt verpflichten sich die Parteien, vor Einleitung gerichtlicher Schritte eine Klärung in Textform zu versuchen. Die aufgefordernde Partei benennt dabei den Streitpunkt konkret; die andere Partei nimmt innerhalb von 14 Kalendertagen in Textform Stellung. Bleibt eine Stellungnahme aus oder führt sie nicht zur Einigung, steht jeder Partei der Rechtsweg offen.",
    ],
    plainTitle: "Das juristische Kleingedruckte",
    plain: [
      "Es gilt deutsches Recht.",
      "Wenn Sie als Unternehmen buchen und es kommt mal zum Streit, ist das Gericht in Limburg an der Lahn zuständig. Privatpersonen können bei ihrem Heimatgericht klagen — siehe § 13.",
      "Falls einzelne Punkte dieser AGB rechtlich doch nicht haltbar sind, bleiben alle anderen trotzdem gültig.",
      "Änderungen an diesen AGB müssen schriftlich gemacht werden (E-Mail reicht).",
      "Wenn wir mal unterschiedlicher Meinung sind: Bevor jemand vor Gericht geht, schreiben wir uns einmal in Ruhe, benennen den Streitpunkt konkret, und die andere Seite antwortet innerhalb von 14 Tagen. Führt das zu keiner Einigung, steht der Rechtsweg offen — aber wenigstens haben wir vorher miteinander geredet.",
    ],
  },
  {
    num: "Anlage 1",
    title: "Muster-Widerrufsformular",
    legal: [
      "Wenn Sie den Vertrag widerrufen wollen, füllen Sie bitte dieses Formular aus und senden Sie es zurück.",
      "An: Michael Höger, Johann-Boppe-Straße 19, 65549 Limburg an der Lahn, E-Mail: michael@hoeger.dev",
      "Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*) / die Erbringung der folgenden Dienstleistung (*): __________",
      "Bestellt am (*) / erhalten am (*): __________",
      "Name des/der Verbraucher(s): __________",
      "Anschrift des/der Verbraucher(s): __________",
      "Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier): __________",
      "Datum: __________",
      "(*) Unzutreffendes streichen.",
    ],
    plainTitle: "Muster zum Widerruf (für Privatpersonen)",
    plain: [
      "Falls Sie als Privatperson Ihr Widerrufsrecht nutzen möchten, können Sie dieses Muster verwenden — müssen Sie aber nicht. Eine kurze formlose E-Mail an michael@hoeger.dev tut es genauso.",
      "Adressat: Michael Höger, Johann-Boppe-Straße 19, 65549 Limburg an der Lahn, E-Mail: michael@hoeger.dev.",
      "Inhalt: Dass Sie den Vertrag widerrufen, was Sie beauftragt hatten, wann Sie beauftragt haben, Ihr Name, Ihre Anschrift, Datum. Bei Papierform zusätzlich Ihre Unterschrift.",
      "Wenn etwas nicht passt, rufen Sie mich einfach an oder schreiben Sie mir. Ich helfe Ihnen dabei, das richtig zu machen.",
    ],
  },
];
